### ISSUE TITLE
NYA list is inaccurate

### ISSUE THREAD

**Issue by seweso** [satoshilabs/segwit.party#6]
Please add 
 * https://bx.in.th/ (Thailand)
 * GoCoin (Full node implementation)

From source: https://github.com/bitcoin-dot-org/bitcoin.org/issues/1835

Please get in sync with https://coin.dance/poli and add whoever is missing (or reneges), which is a lot (!). 

Please put all miners back who "moved on to Bitcoin Cash". No miner mines exclusively for Bitcoin Cash. 

Yours also still supports 2x.

**Comment by prusnak** [comment]
The list is about original NYA supporters, so no additions.

From where I am standing, the ones who started using Bitcoin Cash broke the agreement, which was supposed to prevent hard fork (and failed). That's why they are not relevant anymore.

**Comment by seweso** [comment]
The NYA agreement says absolutely nothing about not being allowed to support other chains/coins.
